### ISSUE TITLE
Some Problem GIFs

### ISSUE THREAD

**Issue by PaintYourDragon** [bitbank2/AnimatedGIF#14]
Working with the lib on Matrix Portal (RGB LED matrix), several small GIFs were having issues either with display glitches or altogether crashes. Wrestled with the Matrix-side code for a while before just trying the same GIFs over on PyPortal, where the player is known to work. Same issues there, so I’m wondering if this is a problem in AnimatedGIF. The images are unusually small (64x32 pixels) if that’s any indication. These all play fine on desktop system / in browser.

Juggler: glitches.
Lightspeed: crash; no frames displayed.
Werewolf: crash; initial frame displayed but nothing further.

These all look a little dark in browser because they’re manually gamma corrected for the way the LED matrix works…this is normal and known and shouldn’t affect anything.

![juggler](https://user-images.githubusercontent.com/887611/97649906-b5b36380-1a15-11eb-8e17-0eb34bb0e30b.gif)
![lightspeed](https://user-images.githubusercontent.com/887611/97649907-b64bfa00-1a15-11eb-9a09-69a1656f9e60.gif)
![werewolf](https://user-images.githubusercontent.com/887611/97649910-b77d2700-1a15-11eb-94dc-e2acb0875469.gif)

**Comment by bitbank2** [comment]
Thanks for the letting me know. Famous quote - "If I can reproduce it, I can fix it" 😄

**Comment by bitbank2** [comment]
Some info... Not a crash, but a normally returned error. The top and bottom images are stored as interlaced and my library rejects them because this code assumes your target CPU doesn't have enough RAM to hold the decoded image. The middle image seems to play correctly.

**Comment by PaintYourDragon** [comment]
Appreciate your help with this today. Got things _mostly_ resolved by de-interlacing all the GIFs through ImageMagick, and handling the different return values from playFrame().

Two images are still causing issues though. (At least they’re not crashing now, thanks to your playFrame() help…but they do get skipped over in the player now when it detects a -1 value, even though they appear valid on desktop.) Attaching them here. These are not necessarily the same as above (even though they look the same in browser)…they’ve been coalesced & deinterlaced through ImageMagick.

![lightspd](https://user-images.githubusercontent.com/887611/97768470-90d7f280-1ae0-11eb-8db3-d7b23d0a5a9b.gif)
![wolf1](https://user-images.githubusercontent.com/887611/97768472-933a4c80-1ae0-11eb-8fdd-237eb0492033.gif)

**Comment by bitbank2** [comment]
On the Mac, both files work correctly; I'll test it on an Arduino board tomorrow. I recently did some fixes to the library, are you sure you're running the latest version?

**Comment by bitbank2** [comment]
I just tested both of your updated files on a TTGO T-Display (ESP32 + ST7789 240x135 LCD) and they both play perfectly.

**Comment by embedded-creations** [comment]
FYI, the latest version of AnimatedGIF has support for interlaced GIFs (thanks Larry!)

**Comment by bitbank2** [comment]
Thanks for helping to test the code :). I should have had interlaced support in from the beginning. I had confused the PNG interlacing with GIF and thought it would break my line-at-a-time code, but it was drop dead simple to add.
