### ISSUE TITLE
1.3.x uses too much RAM to work on SAMD21

### ISSUE THREAD

**Issue by ubidefeo** [bitbank2/AnimatedGIF#25]
A demo by Mirko Pacioni used to compile fine on SAMD21 until `1.2.0`.
I have noticed you considerably upped the buffers on `1.3.0`

__1.2.0__
```
#define LZW_BUF_SIZE (6*MAX_CHUNK_SIZE)
#define LZW_HIGHWATER (4*MAX_CHUNK_SIZE)
#define MAX_WIDTH 320
#define FILE_BUF_SIZE 4096
```
__1.3.0__
``` 
#define LZW_BUF_SIZE (12*MAX_CHUNK_SIZE)
#define LZW_HIGHWATER (10*MAX_CHUNK_SIZE)
#define MAX_WIDTH 320
#define FILE_BUF_SIZE 8192
```

It would be nice to handle these things gracefully if you want to still support the SAMD21 :)

Thank you, mate :)

**Comment by bitbank2** [comment]
Thanks for catching that - it was an experiment to see how it affected the performance on "bigger" systems. I didn't mean to permanently change it. I'll fix it.
