### ISSUE TITLE
linux/main.c: too few arguments to function ‘GIF_begin’

### ISSUE THREAD

**Issue by kamalmostafa** [bitbank2/AnimatedGIF#30]
The linux demo linux/main.c fails to build:

```
main.c:24:5: error: too few arguments to function ‘GIF_begin’
     GIF_begin(&gif, BIG_ENDIAN_PIXELS);
     ^~~~~~~~~
In file included from main.c:8:0:
../src/AnimatedGIF.h:185:10: note: declared here
     void GIF_begin(GIFIMAGE *pGIF, int iEndian , unsigned char ucPaletteType);
          ^~~~~~~~~
```

Patch attached adds `GIF_PALETTE_RGB888` for the missing third arg, allowing the linux demo to build.

Additional note: `{BIG|LITTLE}_ENDIAN_PIXELS` is actually only relevant for `GIF_PALETTE_RGB565`, so perhaps a better scheme would be to switch (back) to a two-arg form for `GIF_begin()` with three constants named e.g.:

```
	GIF_PALETTE_RGB565_BE
	GIF_PALETTE_RGB565_LE
	GIF_PALETTE_RGB888
```

**Comment by bitbank2** [comment]
Thank you for finding this. I like the idea of a single value which specifies the two flavors of RGB565 and RGB888. I'm making the change and will do a new release with another change too.
