### ISSUE TITLE
C Interface declares GIF_getInfo(), implementation provides GIFGetInfo()

### ISSUE THREAD

**Issue by SuperIlu** [bitbank2/AnimatedGIF#32]
See subject :)

**Comment by bitbank2** [comment]
Thanks for pointing it out. I've fixed it and will include it in the next release I'm working on. I'm adding a user defined pointer that can be passed to the GIFDraw callback to allow dynamic info to get there (e.g. placement of the GIF drawing on the screen). I should have it ready later today.

**Comment by SuperIlu** [comment]
Uh, the user defined pointer was a feature I was missing for my project. Looking forward to it, thanks!
