### ISSUE TITLE
Idea to export lottie to GIF

### ISSUE THREAD

**Issue by ajsb85** [bitbank2/AnimatedGIF#33]
You can use [Samsung/rlottie](https://github.com/Samsung/rlottie) library with C-api header

Ref:
https://github.com/Samsung/rlottie/issues/484

**Comment by bitbank2** [comment]
Sorry, but I don't see what rlottie has to do with my AnimatedGIF library. What does "export lottie to GIF" mean exactly? This code is strictly for decoding GIF images on microcontrollers, not for generating GIF images or integrating with any GUI features.

**Comment by ajsb85** [comment]
Yes, I am just trying to motivate to play around.

![image](https://user-images.githubusercontent.com/663460/120527765-0390af80-c3db-11eb-9033-46773ae78d8e.png)

**Comment by bitbank2** [comment]
Please stop spamming my repos
