### ISSUE TITLE
GIFs created with gifencoder.js have trailing zeros, and won't parse correctly

### ISSUE THREAD

**Issue by embedded-creations** [bitbank2/AnimatedGIF#38]
The issue I'm having is specifically with exports from [noisedeck.app](https://noisedeck.app), which I found uses this for encoding GIFs under the hood: https://github.com/jnordberg/gif.js

Three example GIFs:

![noisedeck-1624031604921](https://user-images.githubusercontent.com/1514796/122588144-a5a8cc80-d056-11eb-9129-30b56ead849a.gif)

You can only change the GIF dimensions and number of frames in the pro version
![nd-chlorine-64x64](https://user-images.githubusercontent.com/1514796/122588160-ab061700-d056-11eb-8a82-fbab9436b3a2.gif)

Yes this is ugly but maybe it's useful to have a GIF with just two frames for brevity
![noisedeck-1624029961748](https://user-images.githubusercontent.com/1514796/122588219-bb1df680-d056-11eb-8d9d-2c0b9bc0ac73.gif)

There's trailing zeros left after the end of the GIF:

<img width="706" alt="image" src="https://user-images.githubusercontent.com/1514796/122588380-ef91b280-d056-11eb-872d-8e6dd87660d5.png">

I'm guessing this is a result of the encoder using pages for storage and not trimming the excess at the end.

https://github.com/jnordberg/gif.js/blob/master/src/GIFEncoder.js#L19

`GIFParseInfo()` fails here:

https://github.com/bitbank2/AnimatedGIF/blob/master/src/gif.inl#L401

Here's my quick fix.  There's probably a better place to look for the trailer byte, but this works:

```
        else // invalid byte, stop decoding
        {
            if (pPage->GIFFile.iSize - iStartPos < 32) {
                // non-image bytes at end of file?
                pPage->iError = GIF_EMPTY_FRAME;

            } else if(p[iOffset] == ';') {
                // Trailer Byte - End of the GIF Data Stream
                pPage->iError = GIF_EMPTY_FRAME;
            }
            else {
                /* Bad header info */
                pPage->iError = GIF_DECODE_ERROR;
                Serial.print("byte: ");
                Serial.print(p[iOffset], HEX);
                Serial.print(" pos: ");
                Serial.print(iOffset, HEX);
            }
            return 0;
        }
```

**Comment by bitbank2** [comment]
I did a cleaner fix which correctly handles your test files. Please try my last checkin and let me know if it works for you.

**Comment by bitbank2** [comment]
Open a new issue if you find any other gifs which don't decode correctly.

**Comment by embedded-creations** [comment]
Sorry I didn't have a chance to try until now, the GIFs I was having trouble with work well now, thanks!
