### ISSUE TITLE
Slow down rendering?

### ISSUE THREAD

**Issue by tsctrl** [bitbank2/AnimatedGIF#40]
Hi @bitbank2 ,

based on matrix i2s dma example sketch.
I have issue with gif bouncing right and left, the gif play ok/smooth in pc but in matrix it bouncing and some other gif, 
seems the gif not finish slides from left to the correct position before the frame refresh. sometime i can see the gif slowly entering the frame from the left and then halfway new frame comes in.

i guess maybe the mcu cant keep up or out of ram.
is there way to slow down the rendering or put some delay to make sure proc have time to properly render frame by frame?
i have try to slow down the animation. put 0.2milis delay between frame but didnt work.

thanks in advanced

**Comment by bitbank2** [comment]
There is already code in my library to render the frames at the rate specified in the file. Set the first parameter of playFrame() to true to enable this.
