### ISSUE TITLE
Add support for double buffer mode

### ISSUE THREAD

**Issue by tsctrl** [bitbank2/AnimatedGIF#41]
Hi @bitbank2 ,

wondering if current library could be combine with led matrix double buffer mode?
since double buffer will write the detail on the buffer before swapping the buffer on the screen. from the matrix example, the draw function write pixel by line which i not able to slice the mapping from buffer to the screen. also i not able to control the play and the stop of animation as the playframe are blocking the codes and require to close the running process.

not sure how to make this to work. basically, how to get control on the gif display. should i run the playframe in separate process?

thanks in advanced.

**Comment by bitbank2** [comment]
You can write the pixels into your own buffer and then display them later; the code is built to be flexible. It's not necessary for me to make any changes to the library to accomplish what you're asking.

If you need to quit in the middle of decoding a frame, I could add a feature I recently added to my JPEG library - the draw function returns a bool which indicates if decoding should continue or quit at point.
