### ISSUE TITLE
ESP8266 SPIFFS callbacks

### ISSUE THREAD

**Issue by phanus** [bitbank2/AnimatedGIF#43]
Hello Larry,
thank you for your awesome work. I tried your AnimatedGIF library with ESP32 and ESP8266. With ESP32 and ST7765 display, it works like a charm. Unfortunately for ESP8266 I stuggle with implementation of callbacks for SPIFFS.

```
#include <FS.h>
#include <AnimatedGIF.h>

AnimatedGIF gif;
File f;

void * GIFOpenFile(const char *fname, int32_t *pSize)
{
  f = SPIFFS.open(fname);
  if (f)
  {
    *pSize = f.size();
    return (void *)&f;
  }
  return NULL;
} 

bool displayGIF(char* fname) {
   if (gif.open(fname, GIFOpenFile, GIFCloseFile, GIFReadFile, GIFSeekFile, GIFDraw)) {
      GIFINFO gi;
      Serial.printf("Successfully opened GIF; Canvas size = %d x %d\n", gif.getCanvasWidth(), gif.getCanvasHeight());
      while (gif.playFrame(true, NULL))   {  }
      gif.close();
      return true;
    } else {
      Serial.printf("Error opening file = %d\n", gif.getLastError());
      return false;
    }
}

void setup() {
//SPIFFS and TFT init stuff here

 displayGIF("/test.gif");
}
```
Line ` f = SPIFFS.open(fname);` throws following error during compilation:

D:\Projekty\esp8266-weather-station-color\esp8266-weather-station-color-rad\esp8266-weather-station-color-rad.ino: In function 'void* GIFOpenFile(const char*, int32_t*)':
esp8266-weather-station-color-rad:185:24: error: no matching function for call to 'fs::FS::open(const char*&)'
  185 |   f = SPIFFS.open(fname);
      |                        ^
In file included from sketch\GfxUi.h:22,
                 from D:\Projekty\esp8266-weather-station-color\esp8266-weather-station-color-rad\esp8266-weather-station-color-rad.ino:25:
C:\Users\Petr Hanu�\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\3.0.1\cores\esp8266/FS.h:215:10: note: candidate: 'fs::File fs::FS::open(const char*, const char*)'
  215 |     File open(const char* path, const char* mode);
      |          ^~~~
C:\Users\Petr Hanu�\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\3.0.1\cores\esp8266/FS.h:215:10: note:   candidate expects 2 arguments, 1 provided
C:\Users\Petr Hanu�\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\3.0.1\cores\esp8266/FS.h:216:10: note: candidate: 'fs::File fs::FS::open(const String&, const char*)'
  216 |     File open(const String& path, const char* mode);
      |          ^~~~
C:\Users\Petr Hanu�\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\3.0.1\cores\esp8266/FS.h:216:10: note:   candidate expects 2 arguments, 1 provided
D:\Projekty\esp8266-weather-station-color\esp8266-weather-station-color-rad\esp8266-weather-station-color-rad.ino: In function 'void GIFDraw(GIFDRAW*)':

I'm using Arduino Boards v 2.7.4 or 3.0.1.

I would like to kindly ask you for advice with the callbacks for ESP8266.
Thank you,
Cheers, phanus

**Comment by bitbank2** [comment]
You're neglecting to provide the open mode parameter. The error message is telling you that you're passing 1 argument and the function requires 2. See the documentation here:

https://arduino-esp8266.readthedocs.io/en/latest/filesystem.html#open
