### ISSUE TITLE
A little bug in timing

### ISSUE THREAD

**Issue by BorisFR** [bitbank2/AnimatedGIF#6]
In **playFrame()** 
When call with sync=true, it is ok, but when call with not sync and receive back the delay, you do not do the calculation of time being taken as in the other case.

Actually:

    if (bSync)
    {
        lTime = millis() - lTime;
        if (lTime < _gif.iFrameDelay) // need to pause a bit
            delay(_gif.iFrameDelay - lTime);
    }
    if (delayMilliseconds) // if not NULL, return the frame delay time
            *delayMilliseconds = _gif.iFrameDelay;

It think it must be:

    lTime = millis() - lTime;
    if (bSync)
    {
        if (lTime < _gif.iFrameDelay) // need to pause a bit
            delay(_gif.iFrameDelay - lTime);
    }
    if (delayMilliseconds) // if not NULL, return the frame delay time
    {
        if (lTime < _gif.iFrameDelay) // need to pause a bit
            *delayMilliseconds = _gif.iFrameDelay - lTime;
        else
            *delayMilliseconds = _gif.iFrameDelay;
    }

**Comment by bitbank2** [comment]
The reason I don't return the time in that case is because you've indicated that you want to control the timing, so it's up to you to manage the timing. I was reluctant to even add the delay() inside the library because I want it to be 100% portable to non-Arduino too.
