### ISSUE TITLE
FB datas in 1555 instead of 565

### ISSUE THREAD

**Issue by 0x0fe** [bitbank2/AnimatedGIF#64]
Is there a way to format the FB datas in 1555 instead of 565 or 888? My target FB has alpha channel.

**Comment by bitbank2** [comment]
The pixels are 8-bit with a 24-bit palette lookup. You can configure my existing code to deliver you the original palette and convert the pixels to 1555 yourself. Adding that option within the AnimatedGIF library doesn't make sense to me.

**Comment by 0x0fe** [comment]
i see, but how to get the alpha channel (1bit) value? it is not contained in the 565 or 888.

**Comment by bitbank2** [comment]
There is a single transparent color index per frame and it's part of the data passed to the draw callback (pDraw->ucTransparent). GIF doesn't support any form of alpha channel - it's an optional, single transparent color index.

**Comment by 0x0fe** [comment]
OK clear, yes, i should not call it alpha channel since it is only 1 bit transparent pixel.
