### ISSUE TITLE
Sketch is too big

### ISSUE THREAD

**Issue by Defex111** [bitbank2/AnimatedGIF#67]
When i try to upload a gif i get the following error:
Sketch uses 4047722 bytes (308%) of program storage space. Maximum is 1310720 bytes.
Global variables use 38700 bytes (11%) of dynamic memory, leaving 288980 bytes for local variables. Maximum is 327680 bytes.

is there any way i can fix this?

**Comment by bitbank2** [comment]
A few problems with your issue:

- This has nothing to do with AnimatedGIF
- You don't provide any info about the target MCU or what you're doing

But I'll answer your question.
You can choose to partition the ESP32 memory differently (I assume you're using an ESP32). Under the Tools menu, select "Partition Scheme" and select the one that allows your program to work. If you only have a 4MB FLASH ESP32, then you won't be able to upload that sized code+data and you'll need to put the file(s) somewhere else (uSD card).
