### ISSUE TITLE
Some GIFs have wrong timing animation

### ISSUE THREAD

**Issue by BorisFR** [bitbank2/AnimatedGIF#7]
When using the library, they are too slow.
The common thing I found is that playFrame() tell me to wait 90 or 91 ms for that GIFs. 
![1942](https://user-images.githubusercontent.com/1536092/90401730-ab342f80-e09e-11ea-8648-3a1ae065702c.gif)
![gdarius](https://user-images.githubusercontent.com/1536092/90401738-aff8e380-e09e-11ea-84aa-da4eb6cc51f1.gif)
![pacmaniaingame](https://user-images.githubusercontent.com/1536092/90401775-b8511e80-e09e-11ea-80ab-266c4cebd2f4.gif)

**Comment by bitbank2** [comment]
When an image provides 0 as the frame delay, I return 100ms (10 FPS) because I believe that's the default for browsers. I'll take a look at your images.

**Comment by BorisFR** [comment]
I think you're right.
If I received 100 I then change to 10 and the animation are ok. I have try with 16 but it is still too low. 10 seems to be ok but I don't know the real standard value. Or perhaps it exist a default value in the gif format. My level is not sufficient to help more.

**Comment by bitbank2** [comment]
I pushed a change which allows animation delays of 20ms or more. Please re-test the latest code.

**Comment by BorisFR** [comment]
Sorry for the delay: just test and it is now ok. Thank you.
