### ISSUE TITLE
Stop a GIF mid playing

### ISSUE THREAD

**Issue by mzashh** [bitbank2/AnimatedGIF#70]
Hello, first of all wonderful work with the library, its really helpful 

so is there a command or any way by which i can stop a gif, while its playing
currently by using 
gif.close()

 or  

f = FILESYSTEM.open(fileName); 
f.close();

the gif closes but only after completely playing through, so is there any way to stop it mid way and play the next gif

**Comment by bitbank2** [comment]
The API decodes a frame at a time. You can stop at any frame.
