### ISSUE TITLE
How to display text on GIF for every frame

### ISSUE THREAD

**Issue by mzashh** [bitbank2/AnimatedGIF#71]
Hello, i want to display text or other data on a GIF file so what i did was (for i2C matrix) 

example used https://github.com/mrfaptastic/ESP32-HUB75-MatrixPanel-DMA/tree/master/examples/AnimatedGIFPanel_SPIFFS

modification: in  void GIFDraw  towards the end i added my text like 

    else // does not have transparency
    {
      s = pDraw->pPixels;
      // Translate the 8-bit pixels through the RGB565 palette (already byte reversed)
      for (x=0; x<pDraw->iWidth; x++)
      {
    dma_display->drawPixel(x, y, usPalette[*s++]);}} //color565
    dma_display->setTextSize(2);
    dma_display->setCursor(7, 22); 
    dma_display->print("test"); }  // draw text on GIF 

Issue: but now the issue arises that the text is flickering slightly while as the GIF plays fine in the background.

so is there any better or correct way to do it?

**Comment by bitbank2** [comment]
The concept is very simple - as you decode each line, draw the pixels of the text which should appear on that line on top of the decoded pixels, then send it to the display. No flickering. If you try to draw text on the display AFTER transmitting the GIF pixels, you'll see the flicker.
