### ISSUE TITLE
What happens when there is no palette at all?

### ISSUE THREAD

**Issue by toine512** [bitbank2/AnimatedGIF#77]
Happy new year Mr Bank.

I modified some of the code in order to facilitate handling background transparency hell for my own usage (a Twitch chat connected HUB75 RGB LED matrix).
It occurred to me that the case of an invalid GIF with no palette at all seems to not be handled. \
I don't have the raw GIF crafting knowledge necessary to produce such broken file for testing what actually happens.

In my code I have a flag for global palette existence so I added
```C
else if (!pPage->bHasGlobalPalette) {
  pPage->iError = GIF_BAD_FILE;
  return 0;
}
```
after
```C
if (pPage->ucMap & 0x80) // local color table?
```
in gif.inl.

**Comment by bitbank2** [comment]
It's good of you to try to improve the code. I haven't added checks for every possible failing situation. Can you please open a PR to integrate your changes?
