### ISSUE TITLE
Playing a custom GIF from memory

### ISSUE THREAD

**Issue by SavalioDoesCodingStuff** [bitbank2/AnimatedGIF#80]
I really want to try playing custom GIFs from memory (SD method doesn't work for me), but I don't know how to format them. What I mean by custom GIF is like the GIF played in the `adafruit_gfx_memory.ino` example sketch. I already figured out how to change them just want to know how to make a custom GIF file. Here is how I think the structure of the code works, but I want a confirmation:
`
const uint8_t gifName[] PROGMEM = {
//?? goes here(might be a bitmap, I'm not sure)
};
`
If anybody has done this, could you please recommend a website or a program that converts GIFs into this format. Thank you

**Comment by bitbank2** [comment]
The data given to my library is a GIF file in its entirety, not a bitmap. That's why it's called "AnimatedGIF".  There's nothing special needed, just find a GIF file and pass the data to my library. To generate the C const data from a file, use my image_to_c tool.
