### ISSUE TITLE
Possibility of change GIF speed

### ISSUE THREAD

**Issue by jgauchia** [bitbank2/AnimatedGIF#85]
Hi,

I've a question , 
It's possible to change speed of GIF reproduction?
Thank you!

**Comment by bitbank2** [comment]
You can control that yourself. When you play a frame, you can have the AnimatedGIF library wait for the correct amount of time after each frame or do it yourself:

int AnimatedGIF::playFrame(bool bSync, int *delayMilliseconds, void *pUser)

Pass a pointer to an integer for the second parameter to receive the programmed delay time in millisecond (programmed into the GIF file). If you call it with bSync set to false, it will return immediately after decoding the frame and you can decide if you want to use the requested delay amount or use a different amount of delay.

**Comment by jgauchia** [comment]
Thank you!
