### ISSUE TITLE
turbot_t_qt_example is missing allocFrameBuf() call

### ISSUE THREAD

**Issue by thelastoutpostworkshop** [bitbank2/AnimatedGIF#87]
The example turbot_t_qt_example do not work, allocFrameBuf() is missing.

In the library DecodeLZWTurbo is expecting the frame buffer to be allocated :

    if (pImage->ucDrawType == GIF_DRAW_COOKED && pImage->pfnDraw && pImage->pFrameBuffer) { // convert each line through the palette

So the draw function is never called.

I added the frame buffer allocation in the example to make it work:
      if (gif.allocFrameBuf(GIFAlloc) != GIF_SUCCESS)
      {
        Serial.printf("allocFrameBuf failed\n");
        while (true)
          ;
      }

**Comment by bitbank2** [comment]
I'm not sure if you have a bad copy of the repo or where you got that code. Here's what's currently on GitHub:

https://github.com/bitbank2/AnimatedGIF/blob/542d98dd2dd78769dc1c2aea70969f8f1cce65dd/examples/turbo_t_qt_example/turbo_t_qt_example.ino#L53

It allocates the turbo buffer and then passes it to the library with setTurboBuf().

**Comment by thelastoutpostworkshop** [comment]
Yes I know, but the code of the example do not work if the frame buffer is not allocated, both of them must be allocated based on DecodeLZWTurbo in gif.inl 
if (pImage->ucDrawType == GIF_DRAW_COOKED && pImage->pfnDraw && pImage->pFrameBuffer)

**Comment by bitbank2** [comment]
yes, sorry the turbo decoding needs the framebuffer for cooked output. I'll update the example.

**Comment by bitbank2** [comment]
ok, pushed a fix
