### ISSUE TITLE
Cannot change configuration like MAX_WIDTH

### ISSUE THREAD

**Issue by jrahlf** [bitbank2/AnimatedGIF#91]
Configuration values like `MAX_WIDTH` should be configurable.
Currently one has to modify AnimatedGIF.h.
This means I have to maintain a fork of this repo, if I want to change the values. It would be nice if configuration values would be configurable.

I think the easiest way is to add `#ifndef` around configuration values like `MAX_WIDTH`, so one can provide these as build flags.

**Comment by bitbank2** [comment]
That's a good suggestion. Feel free to do a PR to add it the way you envision.
